server:
  port: 8083
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ON_PARAM
    include-exception: true

app:
  name: "Awesome App"
welcome:
  message: "Hello there, welcome to ${app.name}!"

basic:
  value: true
  message: message
  number: 2

spring:
  filter:
    order: 10
  security:
    user:
      password: myCool_Password

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

jwt:
  secret: mySecretApp
  issuer: demo

